
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
# image list: https://hub.docker.com/r/circleci/php/tags/
#

version: 2.0

jobs:

  deploy-ohh:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install && sudo npm install -g gulp-cli
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - dist
      - run:
          name: Install Jekyll
          command: sudo gem install jekyll
      - run:
          name: Run Gulp
          command: gulp
      - run:
          name: Install rsync
          command: sudo apt install rsync
      - deploy:
          name: Deploy
          command: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-ohh
