
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
# image list: https://hub.docker.com/r/circleci/php/tags/
#

version: 2.0

jobs:

  deploy-ohh:
    docker:
      - image: circleci/php:7.1.20-cli-jessie
    working_directory: ~/project
    dependencies:
      post:
        - bundle exec jekyll build
    steps:
      - checkout
#      - run:
#          name: Install PHP dependencies
#          command: composer install
      - deploy:
          name: Deploy
          command: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-ohh
